import { Database } from './database';

declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    from<K extends keyof Database>(table: K): SupabaseQueryBuilder<Database[K]>;
  }
}

export type { Database };

// This file will be auto-generated by `supabase gen types`
// For now, we'll define the basic types manually

export interface Database {
  public: {
    Tables: {
      restaurant_settings: {
        Row: {
          id: string;
          name: string;
          description: string;
          short_description: string;
          address: string;
          city: string;
          postal_code: string;
          country: string;
          phone: string;
          email: string;
          website: string;
          opening_hours: any[];
          hero_image_url: string | null;
          logo_url: string | null;
          google_maps_url: string | null;
          google_maps_iframe: string | null;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurant_settings']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['restaurant_settings']['Row']>;
      };
      menu_categories: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          display_order: number;
          is_active: boolean;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['menu_categories']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['menu_categories']['Row']>;
      };
      menu_items: {
        Row: {
          id: string;
          category_id: string;
          number: string;
          name: string;
          description: string | null;
          price: number | null;
          price_note: string | null;
          image_url: string | null;
          is_vegetarian: boolean;
          is_vegan: boolean;
          is_gluten_free: boolean;
          is_spicy: boolean;
          is_new: boolean;
          is_recommended: boolean;
          display_order: number;
          is_active: boolean;
          allergen_ids: string[];
          additive_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['menu_items']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['menu_items']['Row']>;
      };
      allergens: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          icon: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['allergens']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['allergens']['Row']>;
      };
      additives: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['additives']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['additives']['Row']>;
      };
      pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          content: string;
          is_active: boolean;
          show_in_navigation: boolean;
          navigation_order: number;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['pages']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['pages']['Row']>;
      };
      languages: {
        Row: {
          id: string;
          code: string;
          name: string;
          is_active: boolean;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['languages']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['languages']['Row']>;
      };
      translations: {
        Row: {
          id: string;
          language_id: string;
          table_name: string;
          record_id: string;
          field_name: string;
          value: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['translations']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['translations']['Row']>;
      };
      users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          role: 'admin' | 'editor' | 'viewer';
          is_active: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['users']['Row']>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTypes<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTypes<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Utility types for query results
export type QueryResult<T> = {
  data: T | null;
  error: Error | null;
};

export type QueryArrayResult<T> = {
  data: T[] | null;
  error: Error | null;
};